### ISSUE TITLE
Failure reporting: how do i get to the expected and actual values?

### ISSUE THREAD

**Issue by azehintense** [mauriciolauffer/wdio-qunit-service#19]
When i run my setup or the vanilla-qunit example (after adding an error) i can't get it to display the expected value and the actual value. It seems to me that because the service tests if the tests passed they look to wdio as tests for a true value. This hides the actual test values underneath. I want them to be displayed, preferably after the qunit output in case the test didn't pass. How do i do this? I tried with hooks but can't get it to work.

**Comment by mauriciolauffer** [comment]
Hey @azehintense , thanks for the feedback. This wasn't possible to do because the QUnit wasn't passing it back.
I was about to release a new version supporting QUnit v1 when I saw this issue last week. I've included a new feature to show the expected and actuals when an assert fails.

This will show up as error logs with the details coming from QUnit:
![image](https://github.com/user-attachments/assets/0093f6b7-5036-431e-bbb0-4ee8d4745019)

![image](https://github.com/user-attachments/assets/81233f62-134e-43ce-b8c9-2009b7c07fbe)

You can also call `await browser.getQUnitResults()` to get the whole report, for instance:
![image](https://github.com/user-attachments/assets/1fb69343-5242-4d0d-aa03-6687e82804b0)
![image](https://github.com/user-attachments/assets/4a9e2f99-f3b9-4a63-ac87-b3c71f106032)

These features and more are available in the just released [v0.3.0](https://github.com/mauriciolauffer/wdio-qunit-service/releases/tag/v0.3.0)
